#! /usr/bin/env python3
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2024-S1-MX-5"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["NGC1333_center_south"] = \
 [ 124077, 124078, 124422, 124423, 124427, 124428,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["NGC1333_center_south"] = "vlsr=-1 dv=10 dw=20 pix_list=-13,15"

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["NGC1333_center_south"] = "pix_list=-13"

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["NGC1333_center_south"] = "pix_list=-4,13,15"

# Found 1 source(s) for 2024-S1-MX-5

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
